In [1]:
import pandas as pd
import re

In [2]:
# --- Day 10: Adapter Array ---
# Patched into the aircraft's data port, you discover weather forecasts of a massive tropical storm. 
# Before you can figure out whether it will impact your vacation plans, however, your device suddenly turns off!

# Its battery is dead.

# You'll need to plug it in. There's only one problem: the charging outlet near your seat produces the wrong number 
# of jolts. Always prepared, you make a list of all of the joltage adapters in your bag.

# Each of your joltage adapters is rated for a specific output joltage (your puzzle input). 
# Any given adapter can take an input 1, 2, or 3 jolts lower than its rating and still produce its rated 
# output joltage.

# In addition, your device has a built-in joltage adapter rated for 3 jolts higher than the highest-rated 
# adapter in your bag. (If your adapter list were 3, 9, and 6, your device's built-in adapter would be rated 
# for 12 jolts.)

# Treat the charging outlet near your seat as having an effective joltage rating of 0.

# Since you have some time to kill, you might as well test all of your adapters. Wouldn't want to get to your resort 
# and realize you can't even charge your device!

# If you use every adapter in your bag at once, what is the distribution of joltage differences between the charging 
# outlet, the adapters, and your device?

# For example, suppose that in your bag, you have adapters with the following joltage ratings:

# 16
# 10
# 15
# 5
# 1
# 11
# 7
# 19
# 6
# 12
# 4
# With these adapters, your device's built-in joltage adapter would be rated for 19 + 3 = 22 jolts, 
# 3 higher than the highest-rated adapter.

# Because adapters can only connect to a source 1-3 jolts lower than its rating, in order to use every adapter, 
# you'd need to choose them like this:

# The charging outlet has an effective rating of 0 jolts, so the only adapters that could connect to it directly 
# would need to have a joltage rating of 1, 2, or 3 jolts. Of these, only one you have is an adapter rated 1 jolt 
# (difference of 1).
# From your 1-jolt rated adapter, the only choice is your 4-jolt rated adapter (difference of 3).
# From the 4-jolt rated adapter, the adapters rated 5, 6, or 7 are valid choices. However, in order to not skip any 
# adapters, you have to pick the adapter rated 5 jolts (difference of 1).
# Similarly, the next choices would need to be the adapter rated 6 and then the adapter rated 7 (with difference of 1
# and 1).
# The only adapter that works with the 7-jolt rated adapter is the one rated 10 jolts (difference of 3).
# From 10, the choices are 11 or 12; choose 11 (difference of 1) and then 12 (difference of 1).
# After 12, only valid adapter has a rating of 15 (difference of 3), then 16 (difference of 1), then 19 
# (difference of 3).
# Finally, your device's built-in adapter is always 3 higher than the highest adapter, so its rating is 22 jolts 
# (always a difference of 3).
# In this example, when using every adapter, there are 7 differences of 1 jolt and 5 differences of 3 jolts.

# Here is a larger example:

# 28
# 33
# 18
# 42
# 31
# 14
# 46
# 20
# 48
# 47
# 24
# 23
# 49
# 45
# 19
# 38
# 39
# 11
# 1
# 32
# 25
# 35
# 8
# 17
# 7
# 9
# 4
# 2
# 34
# 10
# 3
# In this larger example, in a chain that uses all of the adapters, there are 22 
# differences of 1 jolt and 10 differences of 3 jolts.

# Find a chain that uses all of your adapters to connect the charging outlet to your device's 
# built-in adapter and count the joltage differences between the charging outlet, the adapters, and your device. 
# What is the number of 1-jolt differences multiplied by the number of 3-jolt differences?

In [3]:
df = pd.read_excel('adapter.xlsx')
df.head()

   adapter
0       30
1       73
2       84
3      136
4      132

In [4]:
li = list(df.adapter)

li.sort()

len(li)

101

In [5]:
# get list of adapters
li = list(df.adapter)

# set current addapter to 0
current_adapter = 0

# set list of diffs to empty list plus one three for final connection
diffs = [3]

# begin loop
running = True
while running:
    
    # set next adapter to minimun value in adapter list
    next_adapter = min(li)
    
    # remove current min adapter from list of adapters
    li.remove(min(li))
    
    # get differince in current and next adapter values
    diff = next_adapter - current_adapter
   
    # append diff to list of diffs
    diffs.append(diff)
    
    # change adaptor to next addapter
    current_adapter = next_adapter
    
    # break loop if li is empty
    if len(li) == 0:
        
        break
    
# get count of charges
num_one_diff = diffs.count(1)
num_three_diff = diffs.count(3)

# get number of one diffs times number of three diffs
print(num_one_diff," X ",num_three_diff," = ",num_one_diff*num_three_diff)

64  X  37  =  2368

In [6]:
# --- Part Two ---
# To completely determine whether you have enough adapters, you'll need to figure out how many different ways they can be arranged. Every arrangement needs to connect the charging outlet to your device. The previous rules about when adapters can successfully connect still apply.

# The first example above (the one that starts with 16, 10, 15) supports the following arrangements:

# (0), 1, 4, 5, 6, 7, 10, 11, 12, 15, 16, 19, (22)
# (0), 1, 4, 5, 6, 7, 10, 12, 15, 16, 19, (22)
# (0), 1, 4, 5, 7, 10, 11, 12, 15, 16, 19, (22)
# (0), 1, 4, 5, 7, 10, 12, 15, 16, 19, (22)
# (0), 1, 4, 6, 7, 10, 11, 12, 15, 16, 19, (22)
# (0), 1, 4, 6, 7, 10, 12, 15, 16, 19, (22)
# (0), 1, 4, 7, 10, 11, 12, 15, 16, 19, (22)
# (0), 1, 4, 7, 10, 12, 15, 16, 19, (22)
# (The charging outlet and your device's built-in adapter are shown in parentheses.) Given the adapters from 
# the first example, the total number of arrangements that connect the charging outlet to your device is 8.

# The second example above (the one that starts with 28, 33, 18) has many arrangements. Here are a few:

# (0), 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25, 28, 31,
# 32, 33, 34, 35, 38, 39, 42, 45, 46, 47, 48, 49, (52)

# (0), 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25, 28, 31,
# 32, 33, 34, 35, 38, 39, 42, 45, 46, 47, 49, (52)

# (0), 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25, 28, 31,
# 32, 33, 34, 35, 38, 39, 42, 45, 46, 48, 49, (52)

# (0), 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25, 28, 31,
# 32, 33, 34, 35, 38, 39, 42, 45, 46, 49, (52)

# (0), 1, 2, 3, 4, 7, 8, 9, 10, 11, 14, 17, 18, 19, 20, 23, 24, 25, 28, 31,
# 32, 33, 34, 35, 38, 39, 42, 45, 47, 48, 49, (52)

# (0), 3, 4, 7, 10, 11, 14, 17, 20, 23, 25, 28, 31, 34, 35, 38, 39, 42, 45,
# 46, 48, 49, (52)

# (0), 3, 4, 7, 10, 11, 14, 17, 20, 23, 25, 28, 31, 34, 35, 38, 39, 42, 45,
# 46, 49, (52)

# (0), 3, 4, 7, 10, 11, 14, 17, 20, 23, 25, 28, 31, 34, 35, 38, 39, 42, 45,
# 47, 48, 49, (52)

# (0), 3, 4, 7, 10, 11, 14, 17, 20, 23, 25, 28, 31, 34, 35, 38, 39, 42, 45,
# 47, 49, (52)

# (0), 3, 4, 7, 10, 11, 14, 17, 20, 23, 25, 28, 31, 34, 35, 38, 39, 42, 45,
# 48, 49, (52)
# In total, this set of adapters can connect the charging outlet to your device in 19208 distinct arrangements.

# You glance back down at your bag and try to remember why you brought so many adapters; there must be more 
# than a trillion valid ways to arrange them! Surely, there must be an efficient way to count the arrangements.

# What is the total number of distinct ways you can arrange the adapters to connect the charging outlet to your 
# device?

In [7]:
#get max charge
li = list(df.adapter)
max(li)+3

175

In [46]:
# get next connecters
def get_next_charges(current_charges):

    all_charges = list(df.adapter)
    
    next_charges = []

    for charge in current_charges:

        if (charge + 1) in all_charges:

            next_charges.append(charge + 1)

        if (charge + 3) in all_charges:

            next_charges.append(charge + 3)

    return list(set(next_charges))

In [47]:
current_charges = [0]

calculating = True

while calculating:
    
    next_charges = get_next_charges(current_charges)

    print(next_charges)

    current_charges = next_charges

    if len(next_charges) == 0:

        break

[1]
[2]
[5]
[8]
[9, 11]
[10, 12]
[11, 15]
[16, 18, 12]
[17, 21, 15]
[24, 16, 18, 22]
[25, 21, 17, 23]
[24, 18, 28, 22]
[25, 29, 21, 23]
[24, 28, 30, 22]
[25, 23, 29, 33]
[34, 36, 24, 28, 30]
[33, 35, 37, 25, 29]
[34, 36, 40, 28, 30]
[33, 35, 37, 43, 29]
[34, 36, 40, 44, 46, 30]
[33, 35, 37, 43, 45, 49]
[34, 36, 40, 44, 46, 52]
[35, 37, 43, 45, 49, 55]
[36, 40, 44, 46, 52, 56, 58]
[37, 43, 45, 49, 55, 57, 59]
[40, 44, 46, 52, 56, 58, 62]
[65, 43, 45, 49, 55, 57, 59]
[68, 44, 46, 52, 56, 58, 62]
[65, 69, 45, 49, 55, 57, 59]
[68, 72, 46, 52, 56, 58, 62]
[65, 69, 73, 49, 55, 57, 59]
[68, 72, 76, 52, 56, 58, 62]
[65, 69, 73, 79, 55, 57, 59]
[68, 72, 76, 82, 56, 58, 62]
[65, 69, 73, 79, 83, 85, 57, 59]
[68, 72, 76, 82, 84, 88, 58, 62]
[65, 69, 73, 59, 79, 83, 85, 91]
[68, 72, 76, 82, 84, 88, 92, 62]
[65, 69, 73, 79, 83, 85, 91, 93]
[96, 68, 72, 76, 82, 84, 88, 92]
[97, 99, 69, 73, 79, 83, 85, 91, 93]
[96, 98, 102, 72, 76, 82, 84, 88, 92]
[97, 99, 103, 73, 105, 79, 83, 85, 91, 93]
[96, 98, 102, 104, 108, 76, 82, 84, 88, 92]
[97, 99, 103, 105, 109, 79, 83, 85, 91, 93]
[96, 98, 102, 104, 108, 110, 82, 84, 88, 92]
[97, 99, 103, 105, 109, 113, 83, 85, 91, 93]
[96, 98, 102, 104, 108, 110, 116, 84, 88, 92]
[97, 99, 103, 105, 109, 113, 117, 85, 91, 93]
[96, 98, 102, 104, 108, 110, 116, 118, 88, 92]
[97, 99, 103, 105, 109, 113, 117, 121, 91, 93]
[96, 98, 102, 104, 108, 110, 92, 116, 118, 122, 124]
[97, 99, 103, 105, 109, 113, 117, 121, 123, 93, 127]
[96, 98, 130, 102, 104, 108, 110, 116, 118, 122, 124]
[97, 99, 131, 133, 103, 105, 109, 113, 117, 121, 123, 127]
[98, 130, 132, 102, 136, 104, 108, 110, 116, 118, 122, 124]
[99, 131, 133, 103, 105, 139, 109, 113, 117, 121, 123, 127]
[130, 132, 102, 136, 104, 108, 140, 142, 110, 116, 118, 122, 124]
[131, 133, 103, 105, 139, 109, 141, 143, 113, 117, 121, 123, 127]
[130, 132, 136, 104, 108, 140, 142, 110, 146, 116, 118, 122, 124]
[131, 133, 105, 139, 109, 141, 143, 113, 147, 149, 117, 121, 123, 127]
[130, 132, 136, 108, 140, 142, 110, 146, 116, 148, 150, 118, 122, 124]
[121, 131, 133, 139, 109, 141, 143, 113, 147, 149, 117, 153, 123, 127]
[130, 132, 136, 140, 142, 110, 156, 146, 116, 148, 150, 118, 122, 124]
[121, 131, 133, 139, 141, 143, 113, 147, 149, 117, 153, 123, 127, 159]
[160, 130, 162, 132, 136, 140, 142, 156, 146, 116, 148, 150, 118, 122, 124]
[161, 121, 163, 131, 133, 139, 141, 143, 147, 149, 117, 153, 123, 127, 159]
[160, 162, 130, 132, 166, 136, 140, 142, 156, 146, 148, 150, 118, 122, 124]
[161, 121, 163, 131, 133, 169, 139, 141, 143, 147, 149, 153, 123, 127, 159]
[160, 162, 130, 132, 166, 136, 170, 172, 140, 142, 156, 146, 148, 150, 122, 124]
[161, 163, 131, 133, 169, 139, 171, 141, 143, 147, 149, 153, 123, 127, 159]
[160, 162, 130, 132, 166, 136, 170, 172, 140, 142, 124, 146, 148, 150, 156]
[159, 161, 163, 131, 133, 169, 139, 171, 141, 143, 147, 149, 153, 127]
[160, 162, 130, 132, 166, 136, 170, 172, 140, 142, 146, 148, 150, 156]
[161, 163, 131, 133, 169, 139, 171, 141, 143, 147, 149, 153, 159]
[160, 162, 132, 166, 136, 170, 172, 140, 142, 146, 148, 150, 156]
[161, 163, 133, 169, 139, 171, 141, 143, 147, 149, 153, 159]
[160, 162, 166, 136, 170, 172, 140, 142, 146, 148, 150, 156]
[161, 163, 169, 139, 171, 141, 143, 147, 149, 153, 159]
[160, 162, 166, 170, 140, 172, 142, 146, 148, 150, 156]
[161, 163, 169, 171, 141, 143, 147, 149, 153, 159]
[160, 162, 166, 170, 172, 142, 146, 148, 150, 156]
[161, 163, 169, 171, 143, 147, 149, 153, 159]
[160, 162, 166, 170, 172, 146, 148, 150, 156]
[161, 163, 169, 171, 147, 149, 153, 159]
[160, 162, 166, 170, 172, 148, 150, 156]
[161, 163, 169, 171, 149, 153, 159]
[160, 162, 166, 170, 172, 150, 156]
[161, 163, 169, 171, 153, 159]
[160, 162, 166, 170, 172, 156]
[161, 163, 169, 171, 159]
[160, 162, 166, 170, 172]
[169, 161, 163, 171]
[162, 170, 172, 166]
[169, 163, 171]
[170, 172, 166]
[169, 171]
[170, 172]
[171]
[172]
[]

In [38]:
all_charges = list(df.adapter)
all_charges.sort()
all_charges

[0,
 1,
 2,
 5,
 8,
 9,
 10,
 11,
 12,
 15,
 16,
 17,
 18,
 21,
 22,
 23,
 24,
 25,
 28,
 29,
 30,
 33,
 34,
 35,
 36,
 37,
 40,
 43,
 44,
 45,
 46,
 49,
 52,
 55,
 56,
 57,
 58,
 59,
 62,
 65,
 68,
 69,
 72,
 73,
 76,
 79,
 82,
 83,
 84,
 85,
 88,
 91,
 92,
 93,
 96,
 97,
 98,
 99,
 102,
 103,
 104,
 105,
 108,
 109,
 110,
 113,
 116,
 117,
 118,
 121,
 122,
 123,
 124,
 127,
 130,
 131,
 132,
 133,
 136,
 139,
 140,
 141,
 142,
 143,
 146,
 147,
 148,
 149,
 150,
 153,
 156,
 159,
 160,
 161,
 162,
 163,
 166,
 169,
 170,
 171,
 172]

In [8]:
li0 = [1,3]
li1 = [2,4,6]

connections = 0

low_high_con = []

for charge in li0:
    
    if (charge + 1) in li1:
        
        low_high_con.append(charge + 1)
        
    if (charge + 3) in li1:
    
        low_high_con.append(charge + 3)

print(low_high_con)

for charge1 in li1:
    
    for charge2 in li1:
        
        if charge1 >= charge2:
            
            connections += 1
            
connections

[2, 4, 4, 6]

6

In [9]:
def connects_to(value):
    
    li = list(df.adapter)
    
    num_string = ''
       
    con_1 = value + 1

    con_3 = value + 3

    if con_1 in li:

        num_string += str(con_1)

        num_string += ' '

    if con_3 in li:

        num_string += str(con_3)
            
    return num_string.strip()

In [10]:
# def clean(value):
    
#     value = re.sub('\(','',value)
#     value = re.sub('\)','',value)
#     value = re.sub('\,','',value)

In [11]:
df['connects_to'] = df.adapter.apply(connects_to)

In [12]:
df.head()

   adapter connects_to
0       30          33
1       73          76
2       84          85
3      136         139
4      132         133

In [13]:
def get_numbers(value):
    
    return re.findall(r'(\d+)',value)

In [29]:
li = list(df.adapter)

counter = 0

current_adapters = [9, 11]

next_adapters = []

getting_connections = True

# Begin loop

# get list of all possible adaptors for current tier of adapters (begin at 0 adapter)

# get all possible next connections
for ada in current_adapters:

    # create a dataframe showing only adapters that connect to ada
    df_temp = df[df.adapter == ada]

    # get list of possible adapters for next tier of adapters
    li = df_temp.connects_to.apply(get_numbers)
       
    for item in li:
        
        if item not in next_adapters:
            
            next_adapters.append(item)
    
next_adapters
# if list is empty break loop

# count possible tier to tier combinations
# for each current tier adaptor compair it to the list of next tier adapters
# count +1 for each possible connection

# count possible inner tier connections
# count +1 for each adapter in new tier - 1

# set current tier to be equal to new tier

# return counter

[['10', '12'], ['12']]

In [15]:
li = list(df.adapter)

counters = []

current_adapters = [0]

new_adapters = []

getting_connections = True

while getting_connections:

    # get all possible next connections
    for connection in current_connections:
      
        # add column 'contains {bag}' to dataframe 
        df[f'connects_to_{}'] = df.contents.str.contains(bag)

        # create a dataframe showing only rows with a value of true for 'contains {bag}'
        df_temp = df[df[f'contains {bag}'] == True]

        # create a list of bags using the bags column of the dataframe
        li = list(df_temp.bags)

        # add list of bags to bigger_bags
        big_bags.extend(li)
        
        
        
        
        
        
        # get list of bags contained by big_bags 
        df_temp = df[connection in df.connected_to]

        print(df_temp)
        li = list(df_temp.connects_to)[0].strip().split()
        
        print(li)
    break

SyntaxError: f-string: empty expression not allowed (<ipython-input-15-3c93e2e74a10>, line 17)

In [ ]:
if list(df_temp.contents) != []:
        
            li = list(df_temp.contents)[0].strip().split(' ')

            # add list to small bags
            small_bags.extend(li)

    #if small_bags is empty break loop
    if len(small_bags) == 0:

        break

    # add small_bags list to master_list
    total_bags.extend(small_bags)

    # set big_bags equal to small_bags
    big_bags = small_bags

    # set small_bags to empty
    small_bags = []
    
    
# remove all '' from list

while("" in total_bags):
    
    total_bags.remove('')

print(total_bags)

# print number of items in total bags
print(len(total_bags))